### ISSUE TITLE
Z axis doesn't work in Falcon BMS 4.0

### ISSUE THREAD

**Issue by hoover67** [jtsiomb/linuxtrack-wine#2]
Hi folks,

on win7 I'm using the FaceTrackNoIR / Pointtracker for z-axis control in falcon BMS (FOV zoom). 

However this axis won't work in Falcon BMS when running under wine-3.15. All other axes are working fine, just the FOV control via z axis doesn't work.

The z axis is also working fine in linuxtrack's test window, both in 3d and in the axis setting tab. 

Any idea what could be wrong here? 

All the best & thanks a lot for all your hard work! 

Uwe

**Comment by jtsiomb** [comment]
I'm afraid I haven't touched this code for about 7 years now, and I don't remember much. I remember Z-axis tracking used to work fine when I last used this with IL-2 sturmovik. Maybe some change in linuxtrack in the last 7 years broke it? If you ask the linuxtrack guys they might have some notion about whether something changed with the Z axis handling since then.

Uncommenting the logmsg call in ltrnp.c line 160 and `tail -f /tmp/npdll.log` might give a clue about what's going wrong. If Z remains constant then I'm not getting Z axis info from linuxtrack properly. If it changes but still the game doesn't respond, then either I'm not sending it correctly to the game or some other misconfiguration is happening game-side.

Good luck and let me know if you figure something out, or you come up with further questions.

**Comment by hoover67** [comment]
Thanks John, I also contacted Michal about the issue.

All the best, Uwe

**Comment by hoover67** [comment]
Hi John,

sadly Michal hasn't responded yet to my linuxtrack query so here's some
more info:

I ran the "Tester.exe" file using wine and it displays a good range of z
axis values as I'm moving my head towards the screen. All the way back it
reads 1500 and as I move my head to the screen it does down to -1700 or so.

Are these the numbers that you're interested in? While I'm Unix admin of 25
years+ I'm not yet comfortable compiling custom wine plugins in order to
enable the debug / logging statements you mention. :)

I see a slight bit of FOV change when using linuxtrack-wine with falcon BMS
but it's quite small and stops halfway towards the screen (tracking is good
as the Tester.exe indicates the z coords decrease further as I'm moving my
head, just the FOV in BMS doesn't change).

I'd be most grateful for any pointers & ideas you may have.

All the best,

Uwe

**Comment by jtsiomb** [comment]
linuxtrack-wine should just pass the values it gets from linuxtrack to the application through the trackir interface unchanged. It doesn't do any range limiting or anything like that. If there are sensitivity options or limits somewhere in the pipe, they are either at the application side, or linuxtrack itself.

From the numbers you quoted I can guess that the issue you're facing is that the value is clamped to 0 at some point, not allowed to go negative. But again this certainly doesn't happen due to linuxtrack-wine.

As this seems not to be an issue with this project, I'm closing this bug report. If you find some indication that it actually is something linuxtrack-wine is doing wrong, please re-open it and post further information. Otherwise if you think I can help by answering further questions, feel free to mail me directly.
